name: Check Manifest Version Change

on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  check_changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for version change in manifest.json
        run: |
          FILES_CHANGED=$(git diff --name-only ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }})

          if echo "$FILES_CHANGED" | grep -q 'manifest\.json'; then
            CURRENT_VERSION=$(jq -r .version manifest.json)

            if git diff --unified=0 ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} 'manifest.json' | grep -qE "^\+.*\"version\": \"$CURRENT_VERSION\","; then
              echo "Version line in manifest.json has been changed."
            else
              echo "Version line in manifest.json has not been changed."
              exit 1
            fi
          else
            echo "manifest.json has not been changed."
            exit 1
          fi
